package views;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.TreeMap;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

import models.Session;
import models.User;

import controllers.ClientController;

/**
*
* @author Muaad
*/
public class Login extends javax.swing.JFrame {

   /**
    * Creates new form Login
    */
   public Login(ClientController controller) {
	   this.controller = controller;
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

       loginPanel = new javax.swing.JPanel();
       userLabel = new javax.swing.JLabel();
       userTxt = new javax.swing.JTextField();
       passTxt = new JPasswordField();
       passLabel = new javax.swing.JLabel();
       loginButton = new javax.swing.JButton();
       cancelButton = new javax.swing.JButton();
       noAccountLabel = new javax.swing.JLabel();
       signUpButton = new javax.swing.JButton();
       forgotDetailsButton = new javax.swing.JButton();
       logoPanel = new javax.swing.JPanel();
       logoLabel = new javax.swing.JLabel();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       loginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

       userLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
       userLabel.setText("Username");

       passLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
       passLabel.setText("Password");

       loginButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
       loginButton.setText("Login");
       loginButton.addActionListener(new ActionListener() {
		
		@Override
		public void actionPerformed(ActionEvent arg0) {
			System.out.println(userTxt.getText());
			if(User.exists("user_name", userTxt.getText())) {
				if(new String(passTxt.getPassword()).equalsIgnoreCase(User.findBy("user_name", userTxt.getText()).get(0).get("password"))) {
					controller.sessionMap.put("user_id", User.findBy("user_name", userTxt.getText()).get(0).get("id"));
					controller.sessionMap.put("client", userTxt.getText());
					controller.sessionMap.put("logged_in", "YES");
					Session.create(new TreeMap<>(controller.sessionMap));
					controller.sessionMap.put("user_type", User.findBy("user_name", userTxt.getText()).get(0).get("type"));
					controller.displayMainScreen();
				}
				else {
					JOptionPane.showMessageDialog(null, "Username and password don't match!");
				}
			}
			else {
				JOptionPane.showMessageDialog(null, "No such user exists!");
			}
		}
	});

       cancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
       cancelButton.setText("Cancel");

       noAccountLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
       noAccountLabel.setText("Don't have an account?");

       signUpButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
       signUpButton.setForeground(new java.awt.Color(0, 0, 255));
       signUpButton.setText("<html><body style = \"text-decoration:underline;\">Sign Up</body></html>");
       signUpButton.setBorderPainted(false);
       signUpButton.setContentAreaFilled(false);
       signUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseEntered(java.awt.event.MouseEvent evt) {
               signUpButtonMouseEntered(evt);
           }
           public void mouseExited(java.awt.event.MouseEvent evt) {
               signUpButtonMouseExited(evt);
           }
       });
       signUpButton.addActionListener(new ActionListener() {
		
		@Override
		public void actionPerformed(ActionEvent arg0) {
			// TODO Auto-generated method stub
//			controller = new ClientController();
			controller.hideLoginScreen();
			controller.displayRegisterScreen();
//			new SignUp().setVisible(true);
		}
	});

       forgotDetailsButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
       forgotDetailsButton.setForeground(new java.awt.Color(0, 0, 255));
       forgotDetailsButton.setText("<html><body style = \"text-decoration:underline;\">I forgot my details</body></html>");
       forgotDetailsButton.setBorderPainted(false);
       forgotDetailsButton.setContentAreaFilled(false);
       forgotDetailsButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
       forgotDetailsButton.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseEntered(java.awt.event.MouseEvent evt) {
               forgotDetailsButtonMouseEntered(evt);
           }
           public void mouseExited(java.awt.event.MouseEvent evt) {
               forgotDetailsButtonMouseExited(evt);
           }
       });
       forgotDetailsButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               forgotDetailsButtonActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
       loginPanel.setLayout(loginPanelLayout);
       loginPanelLayout.setHorizontalGroup(
           loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(loginPanelLayout.createSequentialGroup()
               .addGap(45, 45, 45)
               .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(loginPanelLayout.createSequentialGroup()
                       .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(38, 38, 38)
                       .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(loginPanelLayout.createSequentialGroup()
                       .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(38, 38, 38)
                       .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(passTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                           .addGroup(loginPanelLayout.createSequentialGroup()
                               .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                               .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
               .addContainerGap(77, Short.MAX_VALUE))
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(noAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(forgotDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(82, 82, 82))
       );
       loginPanelLayout.setVerticalGroup(
           loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(loginPanelLayout.createSequentialGroup()
               .addGap(60, 60, 60)
               .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(userTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                   .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGap(18, 18, 18)
               .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(passTxt)
                   .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(18, 18, 18)
               .addComponent(noAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(forgotDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       logoLabel.setFont(new java.awt.Font("Script MT Bold", 3, 48)); // NOI18N
       logoLabel.setForeground(new java.awt.Color(255, 153, 204));
       logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       logoLabel.setText("Kasoko POS");
       logoLabel.setOpaque(true);

       javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
       logoPanel.setLayout(logoPanelLayout);
       logoPanelLayout.setHorizontalGroup(
           logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );
       logoPanelLayout.setVerticalGroup(
           logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
               .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap())
       );

       pack();
   }// </editor-fold>

   private void signUpButtonMouseEntered(java.awt.event.MouseEvent evt) {
       // TODO add your handling code here:
       signUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
       signUpButton.setText("<html><body style = \"text-decoration:none;\">Sign Up</body></html>");
   }

   private void signUpButtonMouseExited(java.awt.event.MouseEvent evt) {
       // TODO add your handling code here:
       signUpButton.setText("<html><body style = \"text-decoration:underline;\">Sign Up</body></html>");
   }

   private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {

   }

   private void forgotDetailsButtonMouseEntered(java.awt.event.MouseEvent evt) {
       // TODO add your handling code here:
       forgotDetailsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
       forgotDetailsButton.setText("<html><body style = \"text-decoration:none;\">I forgot my details</body></html>");
   }

   private void forgotDetailsButtonMouseExited(java.awt.event.MouseEvent evt) {
       // TODO add your handling code here:
       forgotDetailsButton.setText("<html><body style = \"text-decoration:underline;\">I forgot my details</body></html>");
   }

   private void forgotDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
   }

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
//       try {
//           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//               if ("Nimbus".equals(info.getName())) {
//                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                   break;
//               }
//           }
//       } catch (ClassNotFoundException ex) {
//           java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//       } catch (InstantiationException ex) {
//           java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//       } catch (IllegalAccessException ex) {
//           java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//           java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
//               new Login().setVisible(true);
           }
       });
   }
   // Variables declaration - do not modify
   private javax.swing.JButton cancelButton;
   private javax.swing.JButton forgotDetailsButton;
   private javax.swing.JButton loginButton;
   private javax.swing.JPanel loginPanel;
   private javax.swing.JLabel logoLabel;
   private javax.swing.JPanel logoPanel;
   private javax.swing.JLabel noAccountLabel;
   private javax.swing.JLabel passLabel;
   private JPasswordField passTxt;
   private javax.swing.JButton signUpButton;
   private javax.swing.JLabel userLabel;
   private javax.swing.JTextField userTxt;
   private ClientController controller;
   // End of variables declaration
}

