package views;

import helpers.ViewHelpers;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import models.Business;
import models.User;

import controllers.ClientController;

/**
 *
 * @author Muaad
 */
public class SetUp extends javax.swing.JFrame {

    /**
     * Creates new form SetUp
     */
    public SetUp(ClientController controller) {
    	this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        dbSetUp = new DBSetUp();
        businessSetUp = new BusinessSetUp();
        userSetUp = new UsersSetUp();
        stockSetUp = new StockSetUp();
        card = new CardLayout();
        
        contentPanel.setLayout(new CardLayout());
		contentPanel.add(dbSetUp, "db");
        contentPanel.add(businessSetUp,"business");
        contentPanel.add(userSetUp,"users");
        contentPanel.add(stockSetUp,"stock");
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        logoLabel.setBackground(new java.awt.Color(102, 102, 102));
        logoLabel.setFont(new java.awt.Font("Wide Latin", 3, 48)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
//        logoLabel.setText("Kasoko POS");
        logoLabel.setOpaque(true);

        contentPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        progressBar.setValue(10);

        jLabel2.setText("Crunching everything...");

//        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
//        contentPanel.setLayout(new CardLayout());
//        contentPanelLayout.setHorizontalGroup(
//            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(contentPanelLayout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                    .addGroup(contentPanelLayout.createSequentialGroup()
//                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(0, 0, Short.MAX_VALUE)))
//                .addContainerGap())
//        );
//        contentPanelLayout.setVerticalGroup(
//            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
//                .addGap(0, 450, Short.MAX_VALUE)
//                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(5, 5, 5))
//        );
        
        nextButton.setText("Next");
        nextButton.addActionListener(new ActionListener() {
			int clicks = 1;
			Map<Integer, TreeMap<String, String>> params = new HashMap<Integer, TreeMap<String,String>>();
			TreeMap<String, String> fields;
			@Override
			public void actionPerformed(ActionEvent e) {
//				if (!(clicks > 3)) {
//					ViewHelpers.nextPanel(card, contentPanel);
//					System.out.println(clicks);
//				}
//				else {
//					nextButton.setText("Finish");
//				}
				if (clicks == 1) {
					fields = new TreeMap<String,String>();
					fields.put("ip", dbSetUp.ipTxt.getText());
					fields.put("port", dbSetUp.portTxt.getText());
					params.put(1, fields);
					ViewHelpers.switchPanels(card, contentPanel, "business");
				}
				else if (clicks == 2) {
					if(Business.showAll().size() == 0) {
						if (businessSetUp.nameTxt.getText().equals("") && businessSetUp.locationTxt.getText().equals("")) {
							JOptionPane.showMessageDialog(null, "You need to fill in the business details first!");
							businessSetUp.nameTxt.requestFocus();
						}
						else {
							fields = new TreeMap<String,String>();
							fields.put("name", businessSetUp.nameTxt.getText());
							fields.put("location", businessSetUp.locationTxt.getText());
							fields.put("business_type", businessSetUp.businessTypeCombo.getSelectedItem().toString());
							params.put(2, fields);
							Business.create(fields);
							System.out.println(fields);
							ViewHelpers.switchPanels(card, contentPanel, "users");
						}						
					}
					else {
						if (!(businessSetUp.nameTxt.getText().equals("") && businessSetUp.locationTxt.getText().equals(""))) {
							fields = new TreeMap<String, String>();
							fields.put("name", businessSetUp.nameTxt.getText());
							fields.put("location",
									businessSetUp.locationTxt.getText());
							fields.put("business_type",
									businessSetUp.businessTypeCombo
											.getSelectedItem().toString());
							params.put(2, fields);
							Business.create(fields);
							ViewHelpers.switchPanels(card, contentPanel, "users");
						}
						else {
							ViewHelpers.switchPanels(card, contentPanel, "users");
						}
						
					}
				}
				else if (clicks == 3) {
					if(User.showAll().size() == 0) {
						JOptionPane.showMessageDialog(null, "You need to a user first!");
						userSetUp.firstNameTxt.requestFocus();
					}
					else {
						ViewHelpers.switchPanels(card, contentPanel, "stock");
					}
//					ViewHelpers.switchPanels(card, contentPanel, "stock");
					nextButton.setText("Finish");
				}
				clicks++;
				if(e.getActionCommand() == "Finish") {
					System.out.println(params);
					controller.destroySetUpScreen();
					controller.displayLoginScreen();
				}
			}
		});

        cancelButton.setText("Cancel");

        backButton.setText("Back");
        backButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				ViewHelpers.previousPanel(card, contentPanel);
			}
		});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(cancelButton)
                    .addComponent(backButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
////                new SetUp().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JProgressBar progressBar;
    private DBSetUp dbSetUp;
    private UsersSetUp userSetUp;
    private BusinessSetUp businessSetUp;
    private StockSetUp stockSetUp;
    private CardLayout card;
    private ClientController controller;
    // End of variables declaration
}

