/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JLabel;

/**
 *
 * @author Muaad
 */
public class SetUpProject extends javax.swing.JFrame {

    /**
     * Creates new form SetUpProject
     */
    public SetUpProject() {
        buildPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    void buildPanel() {

        setUpPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblInstructions = new javax.swing.JLabel();
        lblTables = new javax.swing.JLabel();
        buttonCheck = new javax.swing.JButton();
        buttonSetUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setUpPanel.setBackground(new java.awt.Color(0, 51, 102));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lblInstructions.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInstructions.setText("<html><head><body>In order for this program to work correctly, the following tables should be set up." +
        		" Click \"<i>Check</i>\" to see whether they are already set up and \"<i>Set up</i>\" to set them up");

        lblTables.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lblTables.setVerticalAlignment(JLabel.CENTER);
        lblTables.setText("<html><body><table width=\"950\" height=\"1000\" border=\"0\">"+
							"<tr valign=\"top\">"+
							"<td style=\"background-color:#eeeeee;width:15px;text-align:top;\">"+
							"<b>Sales</b>" +
							"<td style=\"background-color:#eeeeee;height:75px;width:500px;text-align:top;\">"+
							"<ul><li>Sales</b></li><li>Transaction History</b></li>" +
									//"<li>Inventory</b></li></ul></td></tr>" +
							
							"<tr><td style=\"background-color:#eeeeee;width:15px;text-align:top;\">"+
							"<b>Expenses</b></td>" +
							"<td style=\"background-color:#eeeeee;height:75px;width:500px;text-align:top;\">"+
							"<ul><li>Expenses</b></li><li>Expenses History</b></li><li>Expense Reasons</b></li></td></tr>" +
							
							"<tr><td style=\"background-color:#eeeeee;width:30px;text-align:top;\">"+
							"<b>Inventory</b></td>" +
							"<td style=\"background-color:#eeeeee;height:75px;width:500px;text-align:top;\">"+
							"<ul><li>Items</li><li>Inventory</li><li>newer_inventory</li></ul></td></tr>"+
							
							"<tr><td style=\"background-color:#eeeeee;width:30px;text-align:top;\">"+
							"<b>Other</b></td>" +
							"<td style=\"background-color:#eeeeee;height:75px;width:500px;text-align:top;\">"+
							"<ul><li>mpesa_customers, mpesa_transaction, withdrawal_charges, deposit_charges</li>" +
							"<li>prepaid_transaction</li><li>postpaid_transaction</li></ul></td></tr>"+
							"</table></body></html>");

        buttonCheck.setBackground(new java.awt.Color(255, 153, 51));
        buttonCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonCheck.setText("Check");
        buttonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheckActionPerformed(evt);
            }
        });

        buttonSetUp.setBackground(new java.awt.Color(255, 153, 51));
        buttonSetUp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonSetUp.setText("Set up");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInstructions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSetUp, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTables, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCheck)
                    .addComponent(buttonSetUp))
                .addContainerGap())
        );

        javax.swing.GroupLayout setUpPanelLayout = new javax.swing.GroupLayout(setUpPanel);
        setUpPanel.setLayout(setUpPanelLayout);
        setUpPanelLayout.setHorizontalGroup(
            setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        setUpPanelLayout.setVerticalGroup(
            setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setUpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    void buttonCheckActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetUpProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetUpProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetUpProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetUpProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetUpProject().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    javax.swing.JButton buttonCheck;
    javax.swing.JButton buttonSetUp;
    javax.swing.JPanel jPanel2;
    javax.swing.JLabel lblInstructions;
    javax.swing.JLabel lblTables;
    javax.swing.JPanel setUpPanel;
    // End of variables declaration
}
